// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmfx1BauiuEMF1O93nQrPbJHeO4GhFkJw',
    appId: '1:956157450116:web:8c0cd7688fffb0c0252fd1',
    messagingSenderId: '956157450116',
    projectId: 'recipe-app-52355',
    authDomain: 'recipe-app-52355.firebaseapp.com',
    storageBucket: 'recipe-app-52355.firebasestorage.app',
    measurementId: 'G-6QF24D9VJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIem27_ALy0EkK1hyaMJTz78lRZfgnYO0',
    appId: '1:956157450116:android:cea6ba45025d084e252fd1',
    messagingSenderId: '956157450116',
    projectId: 'recipe-app-52355',
    storageBucket: 'recipe-app-52355.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz6sKyGfp22lyGTKOSS5dhYWRnBKk36ew',
    appId: '1:956157450116:ios:08d8f2db4b260950252fd1',
    messagingSenderId: '956157450116',
    projectId: 'recipe-app-52355',
    storageBucket: 'recipe-app-52355.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz6sKyGfp22lyGTKOSS5dhYWRnBKk36ew',
    appId: '1:956157450116:ios:08d8f2db4b260950252fd1',
    messagingSenderId: '956157450116',
    projectId: 'recipe-app-52355',
    storageBucket: 'recipe-app-52355.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmfx1BauiuEMF1O93nQrPbJHeO4GhFkJw',
    appId: '1:956157450116:web:db5bd7d5e4d9aed0252fd1',
    messagingSenderId: '956157450116',
    projectId: 'recipe-app-52355',
    authDomain: 'recipe-app-52355.firebaseapp.com',
    storageBucket: 'recipe-app-52355.firebasestorage.app',
    measurementId: 'G-JNHRNSGS2T',
  );
}
